In [1]:
import os
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

In [2]:
ROOT = os.path.join(os.getcwd(), 'Statsbomb_data\open-data-master')
DATA = os.path.join(ROOT, 'data')
FINAL_DF = os.path.join(ROOT,'final_dataframes')

In [3]:
events_df = pd.read_pickle(
    filepath_or_buffer=os.path.join(FINAL_DF,'events.pkl')
)

In [4]:
events_df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'player',
       'position', 'location', 'duration', 'related_events', 'shot',
       'match_id', 'under_pressure', 'out', 'off_camera'],
      dtype='object')

In [5]:
events_df.shot.str['freeze_frame'].iloc[0]

[{'location': [95.6, 35.8],
  'player': {'id': 5216, 'name': 'Andrés Iniesta Luján'},
  'position': {'id': 16, 'name': 'Left Midfield'},
  'teammate': False},
 {'location': [104.3, 45.4],
  'player': {'id': 5211, 'name': 'Jordi Alba Ramos'},
  'position': {'id': 6, 'name': 'Left Back'},
  'teammate': False},
 {'location': [98.5, 27.9],
  'player': {'id': 5542, 'name': 'José Paulo Bezzera Maciel Júnior'},
  'position': {'id': 11, 'name': 'Left Defensive Midfield'},
  'teammate': False},
 {'location': [106.2, 41.7],
  'player': {'id': 5492, 'name': 'Samuel Yves Umtiti'},
  'position': {'id': 5, 'name': 'Left Center Back'},
  'teammate': False},
 {'location': [98.7, 18.8],
  'player': {'id': 5203, 'name': 'Sergio Busquets i Burgos'},
  'position': {'id': 9, 'name': 'Right Defensive Midfield'},
  'teammate': False},
 {'location': [103.0, 23.1],
  'player': {'id': 5213, 'name': 'Gerard Piqué Bernabéu'},
  'position': {'id': 3, 'name': 'Right Center Back'},
  'teammate': False},
 {'location'

# Feature Engineering: Strong Foot

In [87]:
player_df = events_df[['id','player','shot']]

In [88]:
# copy(deep=True) is used to suppress copyWithSetting Warning...
events_df['player_id'] = events_df['player'].str['id']

In [89]:
events_df['player_name'] = events_df['player'].str['name']

In [90]:
events_df['outcome'] = events_df['shot'].str['outcome'].str['name']

In [91]:
events_df['body_part'] = events_df['shot'].str['body_part'].str['name']

In [92]:
player_df['shot'].iloc[0]

{'statsbomb_xg': 0.008752456,
 'end_location': [117.0, 39.7, 1.6],
 'key_pass_id': '430b01dd-eb13-4bf5-8df1-ecd0b76155a0',
 'body_part': {'id': 40, 'name': 'Right Foot'},
 'type': {'id': 87, 'name': 'Open Play'},
 'outcome': {'id': 100, 'name': 'Saved'},
 'technique': {'id': 93, 'name': 'Normal'},
 'freeze_frame': [{'location': [95.6, 35.8],
   'player': {'id': 5216, 'name': 'Andrés Iniesta Luján'},
   'position': {'id': 16, 'name': 'Left Midfield'},
   'teammate': False},
  {'location': [104.3, 45.4],
   'player': {'id': 5211, 'name': 'Jordi Alba Ramos'},
   'position': {'id': 6, 'name': 'Left Back'},
   'teammate': False},
  {'location': [98.5, 27.9],
   'player': {'id': 5542, 'name': 'José Paulo Bezzera Maciel Júnior'},
   'position': {'id': 11, 'name': 'Left Defensive Midfield'},
   'teammate': False},
  {'location': [106.2, 41.7],
   'player': {'id': 5492, 'name': 'Samuel Yves Umtiti'},
   'position': {'id': 5, 'name': 'Left Center Back'},
   'teammate': False},
  {'location': [98

In [93]:
player_df['outcome'] = events_df['shot'].str['outcome'].str['name']

In [94]:
only_goal_df = events_df.loc[player_df['outcome']=='Goal']

In [95]:
player_df

id  \
0      2258c11c-0916-4976-bfde-a66e89ffeb8d   
1      f0be7ddf-1e01-4315-aee1-8d5fda52a739   
2      bb173d27-76c4-4044-b883-8bd6f8450cf2   
3      7b02c827-3580-4149-9912-216ce2bd544f   
4      3b15d864-8738-4cb1-8275-f94277570223   
...                                     ...   
21772  62130924-f82f-4772-a4ef-a11fecaa51c2   
21773  478faba8-6898-4d23-a74c-fa23672e5b50   
21774  222ec97a-066c-4b4f-9bcf-afb4f842edf2   
21775  70094b8a-f6a2-4b9a-8576-36fef59fe44a   
21776  bd2a8d13-4c86-47b3-a8b0-98773a91fee2   

                                                  player  \
0      {'id': 4367, 'name': 'Gonçalo Manuel Ganchinho...   
1          {'id': 6594, 'name': 'Santiago Mina Lorenzo'}   
2               {'id': 5211, 'name': 'Jordi Alba Ramos'}   
3       {'id': 5246, 'name': 'Luis Alberto Suárez Díaz'}   
4      {'id': 4367, 'name': 'Gonçalo Manuel Ganchinho...   
...                                                  ...   
21772               {'id': 39723, 'name': 'Sjaak Swart'}   
21773             {'id': 39724, 'name': 'Gerrie Mühren'}   
21774        {'id': 39717, 'name': 'Roberto Boninsegna'}   
21775          {'id': 39725, 'name': 'Gianfranco Bedin'}   
21776              {'id': 39713, 'name': 'Johan Cruyff'}   

                                                    shot  outcome  
0      {'statsbomb_xg': 0.008752456, 'end_location': ...    Saved  
1      {'statsbomb_xg': 0.05391455, 'end_location': [...  Blocked  
2      {'statsbomb_xg': 0.08084221, 'end_location': [...    Saved  
3      {'statsbomb_xg': 0.45647225, 'end_location': [...     Goal  
4      {'statsbomb_xg': 0.025283428, 'end_location': ...    Saved  
...                                                  ...      ...  
21772  {'statsbomb_xg': 0.03480147, 'end_location': [...    Saved  
21773  {'statsbomb_xg': 0.060509045, 'end_location': ...    Saved  
21774  {'statsbomb_xg': 0.036656085, 'end_location': ...  Blocked  
21775  {'statsbomb_xg': 0.113855265, 'end_location': ...    Off T  
21776  {'statsbomb_xg': 0.08472361, 'end_location': [...  Blocked  

[21777 rows x 4 columns]

In [96]:
player_groups = only_goal_df.groupby(
    by='player_name'
)

In [97]:
strong_foot_mapping = player_groups.agg({'body_part':pd.Series.mode})

In [107]:
strong_foot_mapping.body_part.str

player_name
Abel Gómez Moreno                           Right Foot
Abraham González Casanova                   Right Foot
Adalberto Peñaranda Maestre                 Right Foot
Adnane Tighadouini                          Right Foot
Adriano Correia Claro          [Left Foot, Right Foot]
                                        ...           
Óscar Mingueza García               [Head, Right Foot]
Óscar Rodríguez Arnaiz                      Right Foot
Óscar Serrano Rodriguez                      Left Foot
Óscar de Marcos Arana                       Right Foot
İlkay Gündoğan                              Right Foot
Name: body_part, Length: 524, dtype: object

In [112]:
strong_foot_mapping.body_part.str[0].str.len()

player_name
Abel Gómez Moreno              1
Abraham González Casanova      1
Adalberto Peñaranda Maestre    1
Adnane Tighadouini             1
Adriano Correia Claro          9
                              ..
Óscar Mingueza García          4
Óscar Rodríguez Arnaiz         1
Óscar Serrano Rodriguez        1
Óscar de Marcos Arana          1
İlkay Gündoğan                 1
Name: body_part, Length: 524, dtype: int64

In [113]:
# We need to remove players who have shown same ability for any of the two body parts...
filtered_players = strong_foot_mapping.loc[strong_foot_mapping.body_part.str[0].str.len()==1]

In [114]:
filtered_players.shape

(460, 1)

In [115]:
strong_foot_df=events_df.join(
    other=filtered_players,
    on='player_name',
    how='left',
    rsuffix='_strong'
)

In [116]:
strong_foot_df.shape

(21777, 27)

In [117]:
strong_foot_df.body_part_strong.isnull().sum()

4880

In [118]:
strong_foot_df.body_part_strong.unique()

array([nan, 'Right Foot', 'Left Foot', 'Head', 'Other'], dtype=object)

# Feature Engineering: Within Penalty Area (WPA)

In [119]:
strong_foot_df.loc[
    (strong_foot_df['location'].str[0]>=114)&(strong_foot_df['location'].str[0]<=120) &
    (strong_foot_df['location'].str[1]>=30)&(strong_foot_df['location'].str[1]<=50)
]

id  index  period     timestamp  \
28     304daa7c-374f-484f-b8f5-1cb2f3d77318   3901       2  00:47:03.448   
40     06e8e306-ee41-431e-a3a9-5b2fd2792c27   1571       1  00:33:53.025   
54     6cdccd32-3f38-4e16-82d7-33885cac214b   3117       2  00:25:11.175   
55     dd82ad5d-3c10-4d16-8f6b-4d7c70cf7c31   3237       2  00:27:41.713   
60     8a227f2d-2140-4fab-a687-a6ac8d120626   3589       2  00:36:13.427   
...                                     ...    ...     ...           ...   
21674  4969dea5-a145-44f6-ae0d-74df36be7458   2927       2  00:43:11.227   
21718  bdc9b5af-6b7f-4d09-9005-9c4d34c5bef0   1850       2  00:02:59.957   
21723  3ecbc280-9317-49be-b091-e946a5c7e3da   2666       2  00:26:42.609   
21724  966e642a-6bf6-4cde-8a6a-63807d1a8b5e   2671       2  00:27:06.826   
21768  e9955250-4d52-4f44-9ab3-3070226f8e61   2601       2  00:31:11.512   

       minute  second                        type  possession  \
28         92       3  {'id': 16, 'name': 'Shot'}         190   
40         33      53  {'id': 16, 'name': 'Shot'}          64   
54         70      11  {'id': 16, 'name': 'Shot'}         152   
55         72      41  {'id': 16, 'name': 'Shot'}         155   
60         81      13  {'id': 16, 'name': 'Shot'}         175   
...       ...     ...                         ...         ...   
21674      88      11  {'id': 16, 'name': 'Shot'}         208   
21718      47      59  {'id': 16, 'name': 'Shot'}          95   
21723      71      42  {'id': 16, 'name': 'Shot'}         147   
21724      72       6  {'id': 16, 'name': 'Shot'}         148   
21768      76      11  {'id': 16, 'name': 'Shot'}         203   

                                     possession_team  \
28                   {'id': 207, 'name': 'Valencia'}   
40     {'id': 219, 'name': 'RC Deportivo La Coruña'}   
54     {'id': 219, 'name': 'RC Deportivo La Coruña'}   
55                  {'id': 217, 'name': 'Barcelona'}   
60                  {'id': 217, 'name': 'Barcelona'}   
...                                              ...   
21674                {'id': 24, 'name': 'Liverpool'}   
21718               {'id': 217, 'name': 'Barcelona'}   
21723        {'id': 39, 'name': 'Manchester United'}   
21724        {'id': 39, 'name': 'Manchester United'}   
21768                    {'id': 806, 'name': 'Ajax'}   

                              play_pattern  ... match_id under_pressure  out  \
28       {'id': 1, 'name': 'Regular Play'}  ...     9880           True  NaN   
40        {'id': 2, 'name': 'From Corner'}  ...     9912            NaN  NaN   
54        {'id': 2, 'name': 'From Corner'}  ...     9912           True  NaN   
55       {'id': 6, 'name': 'From Counter'}  ...     9912            NaN  NaN   
60       {'id': 1, 'name': 'Regular Play'}  ...     9912            NaN  NaN   
...                                    ...  ...      ...            ...  ...   
21674     {'id': 2, 'name': 'From Corner'}  ...  3750200            NaN  NaN   
21718    {'id': 1, 'name': 'Regular Play'}  ...  3750201            NaN  NaN   
21723   {'id': 9, 'name': 'From Kick Off'}  ...  3750201            NaN  NaN   
21724     {'id': 2, 'name': 'From Corner'}  ...  3750201            NaN  NaN   
21768  {'id': 3, 'name': 'From Free Kick'}  ...  3750235           True  NaN   

      off_camera  player_id                          player_name  outcome  \
28           NaN       6584                          Simone Zaza    Off T   
40           NaN       5537                   Fabian Lukas Schär    Off T   
54           NaN       6732                 Lucas Pérez Martínez  Blocked   
55           NaN       5246             Luis Alberto Suárez Díaz    Off T   
60           NaN       5503       Lionel Andrés Messi Cuccittini     Goal   
...          ...        ...                                  ...      ...   
21674        NaN      20195                           Dirk Kuijt     Goal   
21718        NaN      15516                        Thierry Henry    Saved   
21723        NaN    

In [120]:
wpa = np.where(
    (strong_foot_df['location'].str[0]>=114)&(strong_foot_df['location'].str[0]<=120) &
    (strong_foot_df['location'].str[1]>=30)&(strong_foot_df['location'].str[1]<=50),
    True,False
)

In [121]:
wpa_df = strong_foot_df

In [122]:
wpa_df['wpa'] = wpa

In [123]:
wpa_df

id  index  period     timestamp  \
0      2258c11c-0916-4976-bfde-a66e89ffeb8d    191       1  00:03:31.114   
1      f0be7ddf-1e01-4315-aee1-8d5fda52a739    383       1  00:07:02.539   
2      bb173d27-76c4-4044-b883-8bd6f8450cf2    654       1  00:13:21.294   
3      7b02c827-3580-4149-9912-216ce2bd544f    700       1  00:14:07.045   
4      3b15d864-8738-4cb1-8275-f94277570223    837       1  00:17:27.953   
...                                     ...    ...     ...           ...   
21772  62130924-f82f-4772-a4ef-a11fecaa51c2   2758       2  00:38:23.735   
21773  478faba8-6898-4d23-a74c-fa23672e5b50   2894       2  00:41:35.267   
21774  222ec97a-066c-4b4f-9bcf-afb4f842edf2   2935       2  00:42:58.282   
21775  70094b8a-f6a2-4b9a-8576-36fef59fe44a   2940       2  00:43:49.185   
21776  bd2a8d13-4c86-47b3-a8b0-98773a91fee2   2991       2  00:45:22.414   

       minute  second                        type  possession  \
0           3      31  {'id': 16, 'name': 'Shot'}          10   
1           7       2  {'id': 16, 'name': 'Shot'}          14   
2          13      21  {'id': 16, 'name': 'Shot'}          25   
3          14       7  {'id': 16, 'name': 'Shot'}          26   
4          17      27  {'id': 16, 'name': 'Shot'}          31   
...       ...     ...                         ...         ...   
21772      83      23  {'id': 16, 'name': 'Shot'}         214   
21773      86      35  {'id': 16, 'name': 'Shot'}         224   
21774      87      58  {'id': 16, 'name': 'Shot'}         227   
21775      88      49  {'id': 16, 'name': 'Shot'}         228   
21776      90      22  {'id': 16, 'name': 'Shot'}         232   

                          possession_team  \
0         {'id': 207, 'name': 'Valencia'}   
1         {'id': 207, 'name': 'Valencia'}   
2        {'id': 217, 'name': 'Barcelona'}   
3        {'id': 217, 'name': 'Barcelona'}   
4         {'id': 207, 'name': 'Valencia'}   
...                                   ...   
21772         {'id': 806, 'name': 'Ajax'}   
21773         {'id': 806, 'name': 'Ajax'}   
21774  {'id': 238, 'name': 'Inter Milan'}   
21775  {'id': 238, 'name': 'Inter Milan'}   
21776         {'id': 806, 'name': 'Ajax'}   

                              play_pattern  ... match_id under_pressure  out  \
0       {'id': 4, 'name': 'From Throw In'}  ...     9880            NaN  NaN   
1      {'id': 3, 'name': 'From Free Kick'}  ...     9880            NaN  NaN   
2       {'id': 4, 'name': 'From Throw In'}  ...     9880            NaN  NaN   
3       {'id': 4, 'name': 'From Throw In'}  ...     9880            NaN  NaN   
4        {'id': 1, 'name': 'Regular Play'}  ...     9880            NaN  NaN   
...                                    ...  ...      ...            ...  ...   
21772  {'id': 3, 'name': 'From Free Kick'}  ...  3750235            NaN  NaN   
21773    {'id': 1, 'name': 'Regular Play'}  ...  3750235            NaN  NaN   
21774    {'id': 1, 'name': 'Regular Play'}  ...  3750235           True  NaN   
21775  {'id': 3, 'name': 'From Free Kick'}  ...  3750235            NaN  NaN   
21776    {'id': 1, 'name': 'Regular Play'}  ...  3750235            NaN  NaN   

      off_camera  player_id                      player_name  outcome  \
0            NaN       4367  Gonçalo Manuel Ganchinho Guedes    Saved   
1            NaN       6594            Santiago Mina Lorenzo  Blocked   
2            NaN       5211                 Jordi Alba Ramos    Saved   
3            NaN       5246         Luis Alberto Suárez Díaz     Goal   
4            NaN       4367  Gonçalo Manuel Ganchinho Guedes    Saved   
...          ...        ...                              ...      ...   
21772        NaN      39723                      Sjaak Swart    Saved   
21773        NaN      39724                    Gerrie Mühren    Saved   
21774        NaN      39717               Roberto Boninsegna  Blocked   
21775        NaN      39725                 Gianfranco Bedin    Off T   
21776        NaN      39713               

# Feature Engineering: Distance from Goal (DFG)

In [124]:
shot_location = wpa_df['location'].to_numpy()

In [125]:
shot_location = np.vstack(shot_location)

In [126]:
shot_location[:,0] # x

array([101. , 103.9, 112.5, ...,  96.1,  96.8, 106.7])

In [127]:
np.sqrt(np.square(shot_location[:,0]-120)+np.square(shot_location[:,1]-40))

array([26.65876966, 19.84363878, 15.88238017, ..., 24.16960902,
       23.24844081, 14.31712262])

In [128]:
distance_from_goal = np.sqrt(np.square(shot_location[:,0]-120)+np.square(shot_location[:,1]-40))

In [129]:
# normalize the distances between 0 and 1
normalized_dfg = (distance_from_goal-np.min(distance_from_goal))/(np.max(distance_from_goal)-np.min(distance_from_goal))

In [130]:
dfg_df = wpa_df
dfg_df['dfg'] = normalized_dfg

In [131]:
dfg_df.head(1)

id  index  period     timestamp  minute  \
0  2258c11c-0916-4976-bfde-a66e89ffeb8d    191       1  00:03:31.114       3   

   second                        type  possession  \
0      31  {'id': 16, 'name': 'Shot'}          10   

                   possession_team                        play_pattern  ...  \
0  {'id': 207, 'name': 'Valencia'}  {'id': 4, 'name': 'From Throw In'}  ...   

  under_pressure  out off_camera player_id                      player_name  \
0            NaN  NaN        NaN      4367  Gonçalo Manuel Ganchinho Guedes   

  outcome   body_part    wpa body_part_strong       dfg  
0   Saved  Right Foot  False              NaN  0.324008  

[1 rows x 28 columns]

# Feature Engineering: Shot Angle

In [132]:
shot_location

array([[101. ,  21.3],
       [103.9,  28.4],
       [112.5,  26. ],
       ...,
       [ 96.1,  36.4],
       [ 96.8,  38.5],
       [106.7,  45.3]])

In [133]:
first_post = [120, 36]
second_post = [120, 44]

In [134]:
# Taken from: https://stackoverflow.com/questions/58953047/issue-with-finding-angle-between-3-points-in-python
v21_0 = first_post[0]-shot_location[:,0]
v21_1 = first_post[1]-shot_location[:,1]
v23_0 = second_post[0]-shot_location[:,0]
v23_1 = second_post[1]-shot_location[:,1]

In [135]:
dot = (v21_0*v23_0) + (v21_1*v23_1)
det = (v21_0*v23_1) - (v21_1*v23_0)

In [136]:
angle = np.rad2deg(np.arctan2(det, dot))

In [137]:
unique_values, counts=np.unique(angle.astype('int'), return_counts=True)

In [138]:
for value, count in zip(unique_values, counts):
    print(f"{value} occurs {count} times")

0 occurs 4 times
1 occurs 5 times
2 occurs 9 times
3 occurs 17 times
4 occurs 17 times
5 occurs 53 times
6 occurs 83 times
7 occurs 116 times
8 occurs 148 times
9 occurs 214 times
10 occurs 380 times
11 occurs 780 times
12 occurs 1041 times
13 occurs 1235 times
14 occurs 1342 times
15 occurs 1253 times
16 occurs 1283 times
17 occurs 1185 times
18 occurs 1082 times
19 occurs 921 times
20 occurs 749 times
21 occurs 652 times
22 occurs 633 times
23 occurs 522 times
24 occurs 469 times
25 occurs 485 times
26 occurs 430 times
27 occurs 372 times
28 occurs 318 times
29 occurs 332 times
30 occurs 322 times
31 occurs 296 times
32 occurs 250 times
33 occurs 236 times
34 occurs 294 times
35 occurs 245 times
36 occurs 375 times
37 occurs 324 times
38 occurs 171 times
39 occurs 218 times
40 occurs 176 times
41 occurs 175 times
42 occurs 154 times
43 occurs 139 times
44 occurs 116 times
45 occurs 116 times
46 occurs 132 times
47 occurs 112 times
48 occurs 111 times
49 occurs 104 times
50 occurs 94 

In [139]:
normalized_angle = (angle-np.min(angle))/(np.max(angle)-np.min(angle))

In [140]:
angle_df = dfg_df
angle_df['angle'] = normalized_angle

In [141]:
angle_df.head(1)

id  index  period     timestamp  minute  \
0  2258c11c-0916-4976-bfde-a66e89ffeb8d    191       1  00:03:31.114       3   

   second                        type  possession  \
0      31  {'id': 16, 'name': 'Shot'}          10   

                   possession_team                        play_pattern  ...  \
0  {'id': 207, 'name': 'Valencia'}  {'id': 4, 'name': 'From Throw In'}  ...   

   out off_camera player_id                      player_name  outcome  \
0  NaN        NaN      4367  Gonçalo Manuel Ganchinho Guedes    Saved   

    body_part    wpa  body_part_strong       dfg     angle  
0  Right Foot  False               NaN  0.324008  0.068101  

[1 rows x 29 columns]

# Feature Engineering: GK Distance from Center of the Goal (GK_Distance)

In [142]:
angle_df['freeze_frame'] = angle_df['shot'].str['freeze_frame']

In [143]:
freeze_frame_df = angle_df[['id','freeze_frame']].explode(
    column='freeze_frame'
)

In [144]:
freeze_frame_df['position_id'] = freeze_frame_df['freeze_frame'].str['position'].str['id']

In [145]:
freeze_frame_df['position_name'] = freeze_frame_df['freeze_frame'].str['position'].str['name']

In [146]:
freeze_frame_df['position_location'] = freeze_frame_df['freeze_frame'].str['location']

In [147]:
freeze_frame_df = freeze_frame_df.loc[freeze_frame_df['position_id']==1]

In [148]:
freeze_frame_df

id  \
0      2258c11c-0916-4976-bfde-a66e89ffeb8d   
1      f0be7ddf-1e01-4315-aee1-8d5fda52a739   
2      bb173d27-76c4-4044-b883-8bd6f8450cf2   
3      7b02c827-3580-4149-9912-216ce2bd544f   
4      3b15d864-8738-4cb1-8275-f94277570223   
...                                     ...   
21772  62130924-f82f-4772-a4ef-a11fecaa51c2   
21773  478faba8-6898-4d23-a74c-fa23672e5b50   
21774  222ec97a-066c-4b4f-9bcf-afb4f842edf2   
21775  70094b8a-f6a2-4b9a-8576-36fef59fe44a   
21776  bd2a8d13-4c86-47b3-a8b0-98773a91fee2   

                                            freeze_frame  position_id  \
0      {'location': [117.4, 37.4], 'player': {'id': 2...          1.0   
1      {'location': [117.3, 37.4], 'player': {'id': 2...          1.0   
2      {'location': [117.1, 34.0], 'player': {'id': 6...          1.0   
3      {'location': [117.6, 42.8], 'player': {'id': 6...          1.0   
4      {'location': [118.6, 38.5], 'player': {'id': 2...          1.0   
...                                                  ...          ...   
21772  {'location': [119.0, 40.4], 'player': {'id': 3...          1.0   
21773  {'location': [118.4, 39.2], 'player': {'id': 3...          1.0   
21774  {'location': [118.6, 39.3], 'player': {'id': 3...          1.0   
21775  {'location': [118.5, 38.1], 'player': {'id': 3...          1.0   
21776  {'location': [118.5, 40.8], 'player': {'id': 3...          1.0   

      position_name position_location  
0        Goalkeeper     [117.4, 37.4]  
1        Goalkeeper     [117.3, 37.4]  
2        Goalkeeper     [117.1, 34.0]  
3        Goalkeeper     [117.6, 42.8]  
4        Goalkeeper     [118.6, 38.5]  
...             ...               ...  
21772    Goalkeeper     [119.0, 40.4]  
21773    Goalkeeper     [118.4, 39.2]  
21774    Goalkeeper     [118.6, 39.3]  
21775    Goalkeeper     [118.5, 38.1]  
21776    Goalkeeper     [118.5, 40.8]  

[21556 rows x 5 columns]

In [149]:
gk_location = freeze_frame_df['position_location'].to_numpy()
gk_location = np.vstack(gk_location)
gk_location

array([[117.4,  37.4],
       [117.3,  37.4],
       [117.1,  34. ],
       ...,
       [118.6,  39.3],
       [118.5,  38.1],
       [118.5,  40.8]])

In [150]:
gk_distance_from_goal = np.sqrt(np.square(gk_location[:,0]-120)+np.square(gk_location[:,1]-40))

In [151]:
normalized_gk_distance_from_goal = (gk_distance_from_goal-np.min(gk_distance_from_goal))/(np.max(gk_distance_from_goal)-np.min(gk_distance_from_goal))

In [152]:
normalized_gk_distance_from_goal

array([0.03945195, 0.04021779, 0.07150238, ..., 0.01679435, 0.02597341,
       0.01824018])

In [153]:
freeze_frame_df['gk_distance'] = normalized_gk_distance_from_goal

In [154]:
freeze_frame_df.head()

id  \
0  2258c11c-0916-4976-bfde-a66e89ffeb8d   
1  f0be7ddf-1e01-4315-aee1-8d5fda52a739   
2  bb173d27-76c4-4044-b883-8bd6f8450cf2   
3  7b02c827-3580-4149-9912-216ce2bd544f   
4  3b15d864-8738-4cb1-8275-f94277570223   

                                        freeze_frame  position_id  \
0  {'location': [117.4, 37.4], 'player': {'id': 2...          1.0   
1  {'location': [117.3, 37.4], 'player': {'id': 2...          1.0   
2  {'location': [117.1, 34.0], 'player': {'id': 6...          1.0   
3  {'location': [117.6, 42.8], 'player': {'id': 6...          1.0   
4  {'location': [118.6, 38.5], 'player': {'id': 2...          1.0   

  position_name position_location  gk_distance  
0    Goalkeeper     [117.4, 37.4]     0.039452  
1    Goalkeeper     [117.3, 37.4]     0.040218  
2    Goalkeeper     [117.1, 34.0]     0.071502  
3    Goalkeeper     [117.6, 42.8]     0.039568  
4    Goalkeeper     [118.6, 38.5]     0.022015

In [155]:
gk_distance_df = angle_df.set_index('id').join(
    other=freeze_frame_df[['id','gk_distance']].set_index('id'),
    on='id',
    how='left'
)

In [156]:
gk_distance_df.head(1)

index  period     timestamp  minute  \
id                                                                          
2258c11c-0916-4976-bfde-a66e89ffeb8d    191       1  00:03:31.114       3   

                                      second                        type  \
id                                                                         
2258c11c-0916-4976-bfde-a66e89ffeb8d      31  {'id': 16, 'name': 'Shot'}   

                                      possession  \
id                                                 
2258c11c-0916-4976-bfde-a66e89ffeb8d          10   

                                                      possession_team  \
id                                                                      
2258c11c-0916-4976-bfde-a66e89ffeb8d  {'id': 207, 'name': 'Valencia'}   

                                                            play_pattern  \
id                                                                         
2258c11c-0916-4976-bfde-a66e89ffeb8d  {'id': 4, 'name': 'From Throw In'}   

                                                                 team  ...  \
id                                                                     ...   
2258c11c-0916-4976-bfde-a66e89ffeb8d  {'id': 207, 'name': 'Valencia'}  ...   

                                     player_id  \
id                                               
2258c11c-0916-4976-bfde-a66e89ffeb8d      4367   

                                                          player_name outcome  \
id                                                                              
2258c11c-0916-4976-bfde-a66e89ffeb8d  Gonçalo Manuel Ganchinho Guedes   Saved   

                                       body_part    wpa body_part_strong  \
id                                                                         
2258c11c-0916-4976-bfde-a66e89ffeb8d  Right Foot  False              NaN   

                                           dfg     angle  \
id                                                         
2258c11c-0916-4976-bfde-a66e89ffeb8d  0.324008  0.068101   

                                                                           freeze_frame  \
id                                                                                        
2258c11c-0916-4976-bfde-a66e89ffeb8d  [{'location': [95.6, 35.8], 'player': {'id': 5...   

                                     gk_distance  
id                                                
2258c11c-0916-4976-bfde-a66e89ffeb8d    0.039452  

[1 rows x 30 columns]

# Feature Engineering: Player positional sub-group

In [157]:
events_df.columns

Index(['id', 'index', 'period', 'timestamp', 'minute', 'second', 'type',
       'possession', 'possession_team', 'play_pattern', 'team', 'player',
       'position', 'location', 'duration', 'related_events', 'shot',
       'match_id', 'under_pressure', 'out', 'off_camera', 'player_id',
       'player_name', 'outcome', 'body_part', 'wpa'],
      dtype='object')

In [158]:
events_df['position'].iloc[0]

{'id': 16, 'name': 'Left Midfield'}

In [159]:
position = {
'Left Midfield': 'Midfield',
'Left Center Forward': 'Attack',
'Left Back': 'Defense',
'Right Back': 'Defense',
'Right Center Forward': 'Attack',
'Left Center Back': 'Defense',
'Right Center Back': 'Defense',
'Right Midfield': 'Midfield',
'Right Defensive Midfield': 'Midfield',
'Left Center Midfield': 'Midfield',
'Right Center Midfield': 'Midfield',
'Left Wing': 'Attack',
'Center Forward': 'Attack',
'Center Attacking Midfield': 'Midfield',
'Center Defensive Midfield': 'Midfield',
'Right Wing': 'Attack',
'Right Wing Back': 'Defense',
'Left Defensive Midfield': 'Midfield',
'Left Wing Back': 'Defense',
'Center Back': 'Defense',
'Secondary Striker': 'Attack',
'Right Attacking Midfield': 'Midfield',
'Left Attacking Midfield': 'Midfield',
'Center Midfield': 'Midfield',
'Goalkeeper': 'Goalkeeper'
}

In [160]:
gk_distance_df['specific_position'] = gk_distance_df['position'].str['name'].map(position)

# Saving final dataframe to pickle

In [161]:
pd.to_pickle(
    obj=gk_distance_df,
    filepath_or_buffer=os.path.join(FINAL_DF,'engineered_features.pkl')
)